# Disable sending stats
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gymonkee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Gymonkee
  #pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'Stripe', '~> 11.2.0'
  pod 'GoogleMaps'  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'


end
